project_id = "axtpbgsjbmhbuqomarcr"

[api]
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
port = 54323

[storage]
file_size_limit = "50MiB"

[auth]
site_url = "https://7fc28aed-a663-4753-8877-1ca39b8ccf8c.lovableproject.com"
additional_redirect_urls = ["https://7fc28aed-a663-4753-8877-1ca39b8ccf8c.lovableproject.com"]
jwt_expiry = 3600
enable_signup = true
# JWT secret should be set as environment variable SUPABASE_JWT_SECRET
# For production, generate a strong secret: openssl rand -base64 32

[auth.email]
enable_signup = true
double_confirm_changes = true

# Public functions - no authentication required
[functions.health]
verify_jwt = false

[functions.get-home-data]
verify_jwt = false

[functions.get-content-details]
verify_jwt = false

# Admin/Import functions - require authentication
[functions.import-data-enhanced]
verify_jwt = true

[functions.scheduled-import]
verify_jwt = true

[functions.import-anime]
verify_jwt = true

[functions.import-manga]
verify_jwt = true

[functions.import-data]
verify_jwt = true

[functions.daily-import]
verify_jwt = true

[functions.temp-anilist-populate-enhanced]
verify_jwt = true

[functions.kitsu-sync-engine-enhanced]
verify_jwt = true

[functions.anilist-enhanced-population]
verify_jwt = true

# Cache functions - require authentication to prevent abuse
[functions.cache-get]
verify_jwt = true

[functions.cache-set]
verify_jwt = true

[functions.cache-utils]
verify_jwt = true

[functions.cached-content-v2]
verify_jwt = true

# Utility functions - require authentication
[functions.anime-api-new]
verify_jwt = true

[functions.check-streaming-availability]
verify_jwt = true